language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  PREFER_LOWEST=""

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: PREFER_LOWEST="--prefer-lowest"

before_script:
  - composer update --no-interaction $PREFER_LOWEST
  - if [ -n "$PREFER_LOWEST" ];then composer update phpunit/phpunit --prefer-source --no-interaction --with-dependencies;fi

script:
  - make test
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/coverage.clover
  - make clean
